-- users 50件 INSERT (Block1)【dummy123】

-- SET @pw1 = '$2a$10$fFvGooy2cuglRez2oJ6TPuP6kKIhxX3sI5Yucs5cjox96D65gis6m';
-- SET @pw2 = '$2a$10$6CvB8jDQ8qzsv5nYeD1hfOTsRy6eXcLmWUSYCtTQRK6TQSBX6iSKi';
-- SET @pw3 = '$2a$10$LNNpT34XGomk6SmxZs/zROmtpqLKYj1WFJsbgx5caX5/C/PObbP0S';
-- SET @pw4 = '$2a$10$3U3ItWIzPiQY5Pja/qvpSuiGmxV6bMngVGD8x96idzA0nYKJ9xUyO';
-- SET @pw5 = '$2a$10$gMV0yVeH0cS0fP9U7j7wve2dCn1dUO5hB8zH7H86YpZJpr9KInCnq';

-- INSERT INTO users (login_id, password_hash, authority, display_name, status) VALUES
-- ('taro01', @pw1, 'USER', 'Taro Sato', 'ACTIVE'),
-- ('hanako02', @pw2, 'USER', 'はなちゃん', 'ACTIVE'),
-- ('kenta03', @pw3, 'USER', 'Kenta Takahashi', 'ACTIVE'),
-- ('ayaka04', @pw4, 'USER', 'あやっち', 'ACTIVE'),
-- ('ryota05', @pw5, 'USER', 'Ryota Ito', 'ACTIVE'),
-- ('haruna06', @pw1, 'USER', 'はるる', 'ACTIVE'),
-- ('shota07', @pw2, 'USER', 'Shota Yamamoto', 'ACTIVE'),
-- ('miyu08', @pw3, 'USER', 'みゆたん', 'ACTIVE'),
-- ('daiki09', @pw4, 'USER', 'Daiki Kobayashi', 'ACTIVE'),
-- ('yui10', @pw5, 'USER', 'ゆいぴ', 'ACTIVE'),
-- ('souta11', @pw1, 'USER', 'Souta Sasaki', 'ACTIVE'),
-- ('hikari12', @pw2, 'USER', 'ひかりん', 'ACTIVE'),
-- ('taiga13', @pw3, 'USER', 'Taiga Shimizu', 'ACTIVE'),
-- ('miku14', @pw4, 'USER', 'みくちょ', 'ACTIVE'),
-- ('ren15', @pw5, 'USER', 'Ren Yamaguchi', 'ACTIVE'),
-- ('riko16', @pw1, 'USER', 'りこぴ', 'ACTIVE'),
-- ('yuta17', @pw2, 'USER', 'Yuta Inoue', 'ACTIVE'),
-- ('hina18', @pw3, 'USER', 'ひなぴ', 'ACTIVE'),
-- ('takumi19', @pw4, 'USER', 'Takumi Hayashi', 'ACTIVE'),
-- ('mei20', @pw5, 'USER', 'めいめい', 'ACTIVE'),
-- ('haruto21', @pw1, 'USER', 'Haruto Mori', 'ACTIVE'),
-- ('sara22', @pw2, 'USER', 'さらりん', 'ACTIVE'),
-- ('yoshiki23', @pw3, 'USER', 'Yoshiki Hashimoto', 'ACTIVE'),
-- ('kana24', @pw4, 'USER', 'かなっち', 'ACTIVE'),
-- ('koki25', @pw5, 'USER', 'Koki Miura', 'ACTIVE'),
-- ('momoka26', @pw1, 'USER', 'ももぴ', 'ACTIVE'),
-- ('toma27', @pw2, 'USER', 'Toma Okamoto', 'ACTIVE'),
-- ('nanami28', @pw3, 'USER', 'ななみん', 'ACTIVE'),
-- ('hayato29', @pw4, 'USER', 'Hayato Murakami', 'ACTIVE'),
-- ('aoi30', @pw5, 'USER', 'あおまる', 'ACTIVE'),
-- ('yuto31', @pw1, 'USER', 'Yuto Kaneko', 'ACTIVE'),
-- ('runa32', @pw2, 'USER', 'るなぴ', 'ACTIVE'),
-- ('minato33', @pw3, 'USER', 'Minato Ishii', 'ACTIVE'),
-- ('noa34', @pw4, 'USER', 'のあち', 'ACTIVE'),
-- ('ryusei35', @pw5, 'USER', 'Ryusei Aoki', 'ACTIVE'),
-- ('hina36', @pw1, 'USER', 'ひなちょ', 'ACTIVE'),
-- ('yuito37', @pw2, 'USER', 'Yuito Sakamoto', 'ACTIVE'),
-- ('sakura38', @pw3, 'USER', 'さくらん', 'ACTIVE'),
-- ('keita39', @pw4, 'USER', 'Keita Yokoyama', 'ACTIVE'),
-- ('mio40', @pw5, 'USER', 'みおたん', 'ACTIVE'),
-- ('taisei41', @pw1, 'USER', 'Taisei Komatsu', 'ACTIVE'),
-- ('hiyori42', @pw2, 'USER', 'ひよりん', 'ACTIVE'),
-- ('rin43', @pw3, 'USER', 'Rin Shibata', 'ACTIVE'),
-- ('atsuki44', @pw4, 'USER', 'あつきち', 'ACTIVE'),
-- ('yura45', @pw5, 'USER', 'Yura Kubo', 'ACTIVE'),
-- ('jun46', @pw1, 'USER', 'じゅんぺ', 'ACTIVE'),
-- ('koharu47', @pw2, 'USER', 'Koharu Takada', 'ACTIVE'),
-- ('seiya48', @pw3, 'USER', 'せいやん', 'ACTIVE'),
-- ('misaki49', @pw4, 'USER', 'Misaki Kurihara', 'ACTIVE'),
-- ('tsubasa50', @pw5, 'USER', 'つばっち', 'ACTIVE');

-- user_profiles 50件 INSERT (Block2)

-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (1,'佐藤','太郎','サトウ','タロウ','8925241','愛知県','横浜市神奈川区','赤坂','5-4-17','パークマンション891','1987-02-14','08080724587','user01@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (2,'鈴木','花子','スズキ','ハナコ','8987711','千葉県','横浜市西区','西新宿','4-7-23',NULL,'2004-04-23','08077010555','user02@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (3,'高橋','健太','タカハシ','ケンタ','2199457','愛知県','福岡市中央区','南幸','2-1-6',NULL,'1997-05-22','08037605245','user03@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (4,'田中','彩花','タナカ','アヤカ','7957503','埼玉県','中央区','西新宿','1-9-5','サンライズマンション715','1987-06-23','08086671325','user04@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (5,'伊藤','涼太','イトウ','リョウタ','8524534','愛知県','大阪市北区','道玄坂','4-2-12','スカイマンション205','1993-11-21','07041152311','user05@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (6,'渡辺','春菜','ワタナベ','ハルナ','1452365','愛知県','横浜市神奈川区','梅田','1-7-2',NULL,'1999-03-04','08086655515','user06@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (7,'山本','翔太','ヤマモト','ショウタ','8900528','千葉県','横浜市神奈川区','栄','3-1-27',NULL,'1997-01-20','08054259753','user07@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (8,'中村','美優','ナカムラ','ミユ','2330848','福岡県','港区','日本橋','3-4-23','パークマンション420','1993-12-10','07037757774','user08@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (9,'小林','大輝','コバヤシ','ダイキ','9728717','愛知県','横浜市神奈川区','梅田','1-10-28','パークマンション339','2004-05-06','07026879493','user09@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (10,'加藤','結衣','カトウ','ユイ','5500098','神奈川県','横浜市神奈川区','道玄坂','5-7-18',NULL,'1984-03-15','08022592246','user10@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (11,'佐々木','蒼太','ササキ','ソウタ','1662921','大阪府','中央区','天神','2-5-7','サンライズマンション869','2001-03-11','08039702259','user11@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (12,'山田','光','ヤマダ','ヒカリ','3613435','東京都','中央区','西新宿','3-4-3',NULL,'2000-02-14','08062188093','user12@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (13,'清水','大河','シミズ','タイガ','8399384','神奈川県','豊島区','赤坂','4-3-19','スカイマンション124','1986-04-10','09074669292','user13@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (14,'吉田','美玖','ヨシダ','ミク','4887957','大阪府','港区','天神','2-3-17',NULL,'1997-11-26','08011420763','user14@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (15,'山口','廉','ヤマグチ','レン','8799979','福岡県','福岡市中央区','反町','1-5-9','グリーンマンション342','1995-02-06','07093301684','user15@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (16,'松本','莉子','マツモト','リコ','9050212','埼玉県','名古屋市中区','道玄坂','4-9-10',NULL,'1983-12-16','08002452774','user16@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (17,'井上','優太','イノウエ','ユウタ','4010475','埼玉県','横浜市西区','道玄坂','2-6-30','グリーンマンション688','1984-03-08','09011055776','user17@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (18,'木村','陽菜','キムラ','ヒナ','1094953','愛知県','横浜市西区','日本橋','4-3-27','パークマンション855','2002-07-22','08056249568','user18@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (19,'林','拓海','ハヤシ','タクミ','1383408','愛知県','中央区','梅田','2-11-20',NULL,'2001-01-08','09057950757','user19@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (20,'斉藤','芽衣','サイトウ','メイ','6453467','埼玉県','港区','池袋','2-8-6','パークマンション348','1998-07-09','09022468706','user20@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (21,'森','陽斗','モリ','ハルト','8789724','福岡県','港区','道玄坂','2-12-25','グリーンマンション195','1981-04-05','08026478790','user21@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (22,'阿部','紗良','アベ','サラ','9057779','福岡県','横浜市神奈川区','日本橋','1-9-16',NULL,'1996-09-17','09095233011','user22@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (23,'橋本','義樹','ハシモト','ヨシキ','7561387','大阪府','大阪市北区','池袋','2-6-26','パークマンション629','1989-03-18','09033083447','user23@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (24,'石原','佳奈','イシハラ','カナ','6688338','埼玉県','港区','日本橋','2-2-12','グリーンマンション209','1992-12-25','09070059909','user24@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (25,'三浦','航輝','ミウラ','コウキ','9545304','愛知県','渋谷区','赤坂','2-5-21','スカイマンション703','2000-08-12','09043954794','user25@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (26,'福田','桃花','フクダ','モモカ','4829904','大阪府','横浜市西区','赤坂','4-8-17',NULL,'1990-01-07','07026056733','user26@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (27,'岡本','斗真','オカモト','トウマ','5141808','神奈川県','福岡市中央区','赤坂','3-4-14',NULL,'1987-11-06','09086630199','user27@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (28,'上田','七海','ウエダ','ナナミ','1627600','東京都','大阪市北区','南幸','3-4-22','サンライズマンション651','1997-12-19','08062962535','user28@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (29,'村上','隼人','ムラカミ','ハヤト','5060785','神奈川県','横浜市神奈川区','南幸','4-12-4',NULL,'2000-04-09','07090612125','user29@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (30,'太田','葵','オオタ','アオイ','2066332','神奈川県','中央区','梅田','1-1-3','スカイマンション438','1993-02-15','09022779931','user30@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (31,'金子','悠斗','カネコ','ユウト','5313689','愛知県','横浜市西区','道玄坂','2-8-19','パークマンション356','1987-01-22','07032149413','user31@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (32,'藤井','瑠奈','フジイ','ルナ','8329380','埼玉県','横浜市西区','道玄坂','2-9-30','サンライズマンション820','1994-10-07','09041886355','user32@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (33,'石井','湊','イシイ','ミナト','6076945','千葉県','新宿区','道玄坂','1-2-4','スカイマンション302','1985-10-28','09080835229','user33@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (34,'遠藤','乃愛','エンドウ','ノア','6190193','福岡県','豊島区','道玄坂','4-1-28',NULL,'2001-03-26','09014675127','user34@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (35,'青木','琉生','アオキ','リュウセイ','7530914','大阪府','名古屋市中区','南幸','4-11-21','グリーンマンション274','1992-04-23','07037511737','user35@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (36,'中島','日菜','ナカジマ','ヒナ','5599728','埼玉県','横浜市西区','栄','5-12-9','サンライズマンション843','2003-02-28','09017227627','user36@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (37,'坂本','結人','サカモト','ユイト','1585388','神奈川県','中央区','道玄坂','1-10-27','グリーンマンション446','1992-06-14','07056413908','user37@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (38,'前田','桜','マエダ','サクラ','6980939','埼玉県','中央区','池袋','4-11-18',NULL,'1989-02-13','07033284252','user38@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (39,'横山','惠太','ヨコヤマ','ケイタ','4960717','福岡県','中央区','反町','4-3-1',NULL,'2004-01-24','09003762444','user39@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (40,'長谷川','美桜','ハセガワ','ミオ','9962410','千葉県','中央区','西新宿','1-6-10','パークマンション534','1983-03-06','09091372082','user40@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (41,'小松','大成','コマツ','タイセイ','7437478','福岡県','名古屋市中区','西新宿','1-2-8','スカイマンション785','1988-04-21','09085267109','user41@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (42,'竹内','ひより','タケウチ','ヒヨリ','5744370','大阪府','横浜市西区','栄','5-1-18',NULL,'1995-09-15','07042706259','user42@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (43,'柴田','凛','シバタ','リン','7400787','福岡県','港区','道玄坂','2-10-16','サンライズマンション310','1994-04-07','08003476097','user43@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (44,'平野','篤輝','ヒラノ','アツキ','4139342','東京都','福岡市中央区','栄','5-7-12',NULL,'1993-05-25','07030388324','user44@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (45,'久保','由良','クボ','ユラ','4037482','大阪府','渋谷区','西新宿','3-9-9','サンライズマンション115','1992-03-24','08066959477','user45@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (46,'和田','淳','ワダ','ジュン','3830067','東京都','横浜市神奈川区','道玄坂','3-4-29','サンライズマンション517','1985-05-18','07091345949','user46@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (47,'高田','小春','タカダ','コハル','9524218','大阪府','大阪市北区','栄','1-5-10',NULL,'1986-01-18','07018051418','user47@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (48,'川口','星也','カワグチ','セイヤ','5125515','愛知県','福岡市中央区','梅田','5-1-5',NULL,'1998-08-14','08086492833','user48@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (49,'栗原','美咲','クリハラ','ミサキ','7108712','東京都','港区','池袋','4-10-16',NULL,'1991-06-28','08048037255','user49@example.com');
-- INSERT INTO user_profiles (user_id,last_name,first_name,last_name_kana,first_name_kana,postal_code,prefecture,city,town,address_number,building,birthday,phone_number,email) VALUES (50,'永井','翼','ナガイ','ツバサ','6427571','福岡県','福岡市中央区','西新宿','1-11-22','パークマンション435','1998-04-28','08038537488','user50@example.com');

-- books 100 synthetic entries

-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1001','9780000000001','Sample Book Title 1','Author 1','Sample Publisher','2001','This is a sample description for book 1.','https://example.com/thumbvol1001.jpg','https://example.com/previewvol1001');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1002','9780000000002','Sample Book Title 2','Author 2','Sample Publisher','2002','This is a sample description for book 2.','https://example.com/thumbvol1002.jpg','https://example.com/previewvol1002');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1003','9780000000003','Sample Book Title 3','Author 3','Sample Publisher','2003','This is a sample description for book 3.','https://example.com/thumbvol1003.jpg','https://example.com/previewvol1003');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1004','9780000000004','Sample Book Title 4','Author 4','Sample Publisher','2004','This is a sample description for book 4.','https://example.com/thumbvol1004.jpg','https://example.com/previewvol1004');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1005','9780000000005','Sample Book Title 5','Author 5','Sample Publisher','2005','This is a sample description for book 5.','https://example.com/thumbvol1005.jpg','https://example.com/previewvol1005');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1006','9780000000006','Sample Book Title 6','Author 6','Sample Publisher','2006','This is a sample description for book 6.','https://example.com/thumbvol1006.jpg','https://example.com/previewvol1006');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1007','9780000000007','Sample Book Title 7','Author 7','Sample Publisher','2007','This is a sample description for book 7.','https://example.com/thumbvol1007.jpg','https://example.com/previewvol1007');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1008','9780000000008','Sample Book Title 8','Author 8','Sample Publisher','2008','This is a sample description for book 8.','https://example.com/thumbvol1008.jpg','https://example.com/previewvol1008');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1009','9780000000009','Sample Book Title 9','Author 9','Sample Publisher','2009','This is a sample description for book 9.','https://example.com/thumbvol1009.jpg','https://example.com/previewvol1009');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1010','9780000000010','Sample Book Title 10','Author 10','Sample Publisher','2010','This is a sample description for book 10.','https://example.com/thumbvol1010.jpg','https://example.com/previewvol1010');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1011','9780000000011','Sample Book Title 11','Author 11','Sample Publisher','2011','This is a sample description for book 11.','https://example.com/thumbvol1011.jpg','https://example.com/previewvol1011');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1012','9780000000012','Sample Book Title 12','Author 12','Sample Publisher','2012','This is a sample description for book 12.','https://example.com/thumbvol1012.jpg','https://example.com/previewvol1012');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1013','9780000000013','Sample Book Title 13','Author 13','Sample Publisher','2013','This is a sample description for book 13.','https://example.com/thumbvol1013.jpg','https://example.com/previewvol1013');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1014','9780000000014','Sample Book Title 14','Author 14','Sample Publisher','2014','This is a sample description for book 14.','https://example.com/thumbvol1014.jpg','https://example.com/previewvol1014');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1015','9780000000015','Sample Book Title 15','Author 15','Sample Publisher','2015','This is a sample description for book 15.','https://example.com/thumbvol1015.jpg','https://example.com/previewvol1015');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1016','9780000000016','Sample Book Title 16','Author 16','Sample Publisher','2016','This is a sample description for book 16.','https://example.com/thumbvol1016.jpg','https://example.com/previewvol1016');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1017','9780000000017','Sample Book Title 17','Author 17','Sample Publisher','2017','This is a sample description for book 17.','https://example.com/thumbvol1017.jpg','https://example.com/previewvol1017');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1018','9780000000018','Sample Book Title 18','Author 18','Sample Publisher','2018','This is a sample description for book 18.','https://example.com/thumbvol1018.jpg','https://example.com/previewvol1018');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1019','9780000000019','Sample Book Title 19','Author 19','Sample Publisher','2019','This is a sample description for book 19.','https://example.com/thumbvol1019.jpg','https://example.com/previewvol1019');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1020','9780000000020','Sample Book Title 20','Author 20','Sample Publisher','2000','This is a sample description for book 20.','https://example.com/thumbvol1020.jpg','https://example.com/previewvol1020');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1021','9780000000021','Sample Book Title 21','Author 21','Sample Publisher','2001','This is a sample description for book 21.','https://example.com/thumbvol1021.jpg','https://example.com/previewvol1021');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1022','9780000000022','Sample Book Title 22','Author 22','Sample Publisher','2002','This is a sample description for book 22.','https://example.com/thumbvol1022.jpg','https://example.com/previewvol1022');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1023','9780000000023','Sample Book Title 23','Author 23','Sample Publisher','2003','This is a sample description for book 23.','https://example.com/thumbvol1023.jpg','https://example.com/previewvol1023');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1024','9780000000024','Sample Book Title 24','Author 24','Sample Publisher','2004','This is a sample description for book 24.','https://example.com/thumbvol1024.jpg','https://example.com/previewvol1024');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1025','9780000000025','Sample Book Title 25','Author 25','Sample Publisher','2005','This is a sample description for book 25.','https://example.com/thumbvol1025.jpg','https://example.com/previewvol1025');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1026','9780000000026','Sample Book Title 26','Author 26','Sample Publisher','2006','This is a sample description for book 26.','https://example.com/thumbvol1026.jpg','https://example.com/previewvol1026');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1027','9780000000027','Sample Book Title 27','Author 27','Sample Publisher','2007','This is a sample description for book 27.','https://example.com/thumbvol1027.jpg','https://example.com/previewvol1027');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1028','9780000000028','Sample Book Title 28','Author 28','Sample Publisher','2008','This is a sample description for book 28.','https://example.com/thumbvol1028.jpg','https://example.com/previewvol1028');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1029','9780000000029','Sample Book Title 29','Author 29','Sample Publisher','2009','This is a sample description for book 29.','https://example.com/thumbvol1029.jpg','https://example.com/previewvol1029');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1030','9780000000030','Sample Book Title 30','Author 30','Sample Publisher','2010','This is a sample description for book 30.','https://example.com/thumbvol1030.jpg','https://example.com/previewvol1030');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1031','9780000000031','Sample Book Title 31','Author 31','Sample Publisher','2011','This is a sample description for book 31.','https://example.com/thumbvol1031.jpg','https://example.com/previewvol1031');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1032','9780000000032','Sample Book Title 32','Author 32','Sample Publisher','2012','This is a sample description for book 32.','https://example.com/thumbvol1032.jpg','https://example.com/previewvol1032');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1033','9780000000033','Sample Book Title 33','Author 33','Sample Publisher','2013','This is a sample description for book 33.','https://example.com/thumbvol1033.jpg','https://example.com/previewvol1033');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1034','9780000000034','Sample Book Title 34','Author 34','Sample Publisher','2014','This is a sample description for book 34.','https://example.com/thumbvol1034.jpg','https://example.com/previewvol1034');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1035','9780000000035','Sample Book Title 35','Author 35','Sample Publisher','2015','This is a sample description for book 35.','https://example.com/thumbvol1035.jpg','https://example.com/previewvol1035');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1036','9780000000036','Sample Book Title 36','Author 36','Sample Publisher','2016','This is a sample description for book 36.','https://example.com/thumbvol1036.jpg','https://example.com/previewvol1036');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1037','9780000000037','Sample Book Title 37','Author 37','Sample Publisher','2017','This is a sample description for book 37.','https://example.com/thumbvol1037.jpg','https://example.com/previewvol1037');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1038','9780000000038','Sample Book Title 38','Author 38','Sample Publisher','2018','This is a sample description for book 38.','https://example.com/thumbvol1038.jpg','https://example.com/previewvol1038');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1039','9780000000039','Sample Book Title 39','Author 39','Sample Publisher','2019','This is a sample description for book 39.','https://example.com/thumbvol1039.jpg','https://example.com/previewvol1039');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1040','9780000000040','Sample Book Title 40','Author 40','Sample Publisher','2000','This is a sample description for book 40.','https://example.com/thumbvol1040.jpg','https://example.com/previewvol1040');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1041','9780000000041','Sample Book Title 41','Author 41','Sample Publisher','2001','This is a sample description for book 41.','https://example.com/thumbvol1041.jpg','https://example.com/previewvol1041');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1042','9780000000042','Sample Book Title 42','Author 42','Sample Publisher','2002','This is a sample description for book 42.','https://example.com/thumbvol1042.jpg','https://example.com/previewvol1042');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1043','9780000000043','Sample Book Title 43','Author 43','Sample Publisher','2003','This is a sample description for book 43.','https://example.com/thumbvol1043.jpg','https://example.com/previewvol1043');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1044','9780000000044','Sample Book Title 44','Author 44','Sample Publisher','2004','This is a sample description for book 44.','https://example.com/thumbvol1044.jpg','https://example.com/previewvol1044');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1045','9780000000045','Sample Book Title 45','Author 45','Sample Publisher','2005','This is a sample description for book 45.','https://example.com/thumbvol1045.jpg','https://example.com/previewvol1045');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1046','9780000000046','Sample Book Title 46','Author 46','Sample Publisher','2006','This is a sample description for book 46.','https://example.com/thumbvol1046.jpg','https://example.com/previewvol1046');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1047','9780000000047','Sample Book Title 47','Author 47','Sample Publisher','2007','This is a sample description for book 47.','https://example.com/thumbvol1047.jpg','https://example.com/previewvol1047');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1048','9780000000048','Sample Book Title 48','Author 48','Sample Publisher','2008','This is a sample description for book 48.','https://example.com/thumbvol1048.jpg','https://example.com/previewvol1048');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1049','9780000000049','Sample Book Title 49','Author 49','Sample Publisher','2009','This is a sample description for book 49.','https://example.com/thumbvol1049.jpg','https://example.com/previewvol1049');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1050','9780000000050','Sample Book Title 50','Author 50','Sample Publisher','2010','This is a sample description for book 50.','https://example.com/thumbvol1050.jpg','https://example.com/previewvol1050');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1051','9780000000051','Sample Book Title 51','Author 51','Sample Publisher','2011','This is a sample description for book 51.','https://example.com/thumbvol1051.jpg','https://example.com/previewvol1051');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1052','9780000000052','Sample Book Title 52','Author 52','Sample Publisher','2012','This is a sample description for book 52.','https://example.com/thumbvol1052.jpg','https://example.com/previewvol1052');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1053','9780000000053','Sample Book Title 53','Author 53','Sample Publisher','2013','This is a sample description for book 53.','https://example.com/thumbvol1053.jpg','https://example.com/previewvol1053');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1054','9780000000054','Sample Book Title 54','Author 54','Sample Publisher','2014','This is a sample description for book 54.','https://example.com/thumbvol1054.jpg','https://example.com/previewvol1054');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1055','9780000000055','Sample Book Title 55','Author 55','Sample Publisher','2015','This is a sample description for book 55.','https://example.com/thumbvol1055.jpg','https://example.com/previewvol1055');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1056','9780000000056','Sample Book Title 56','Author 56','Sample Publisher','2016','This is a sample description for book 56.','https://example.com/thumbvol1056.jpg','https://example.com/previewvol1056');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1057','9780000000057','Sample Book Title 57','Author 57','Sample Publisher','2017','This is a sample description for book 57.','https://example.com/thumbvol1057.jpg','https://example.com/previewvol1057');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1058','9780000000058','Sample Book Title 58','Author 58','Sample Publisher','2018','This is a sample description for book 58.','https://example.com/thumbvol1058.jpg','https://example.com/previewvol1058');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1059','9780000000059','Sample Book Title 59','Author 59','Sample Publisher','2019','This is a sample description for book 59.','https://example.com/thumbvol1059.jpg','https://example.com/previewvol1059');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1060','9780000000060','Sample Book Title 60','Author 60','Sample Publisher','2000','This is a sample description for book 60.','https://example.com/thumbvol1060.jpg','https://example.com/previewvol1060');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1061','9780000000061','Sample Book Title 61','Author 61','Sample Publisher','2001','This is a sample description for book 61.','https://example.com/thumbvol1061.jpg','https://example.com/previewvol1061');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1062','9780000000062','Sample Book Title 62','Author 62','Sample Publisher','2002','This is a sample description for book 62.','https://example.com/thumbvol1062.jpg','https://example.com/previewvol1062');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1063','9780000000063','Sample Book Title 63','Author 63','Sample Publisher','2003','This is a sample description for book 63.','https://example.com/thumbvol1063.jpg','https://example.com/previewvol1063');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1064','9780000000064','Sample Book Title 64','Author 64','Sample Publisher','2004','This is a sample description for book 64.','https://example.com/thumbvol1064.jpg','https://example.com/previewvol1064');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1065','9780000000065','Sample Book Title 65','Author 65','Sample Publisher','2005','This is a sample description for book 65.','https://example.com/thumbvol1065.jpg','https://example.com/previewvol1065');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1066','9780000000066','Sample Book Title 66','Author 66','Sample Publisher','2006','This is a sample description for book 66.','https://example.com/thumbvol1066.jpg','https://example.com/previewvol1066');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1067','9780000000067','Sample Book Title 67','Author 67','Sample Publisher','2007','This is a sample description for book 67.','https://example.com/thumbvol1067.jpg','https://example.com/previewvol1067');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1068','9780000000068','Sample Book Title 68','Author 68','Sample Publisher','2008','This is a sample description for book 68.','https://example.com/thumbvol1068.jpg','https://example.com/previewvol1068');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1069','9780000000069','Sample Book Title 69','Author 69','Sample Publisher','2009','This is a sample description for book 69.','https://example.com/thumbvol1069.jpg','https://example.com/previewvol1069');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1070','9780000000070','Sample Book Title 70','Author 70','Sample Publisher','2010','This is a sample description for book 70.','https://example.com/thumbvol1070.jpg','https://example.com/previewvol1070');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1071','9780000000071','Sample Book Title 71','Author 71','Sample Publisher','2011','This is a sample description for book 71.','https://example.com/thumbvol1071.jpg','https://example.com/previewvol1071');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1072','9780000000072','Sample Book Title 72','Author 72','Sample Publisher','2012','This is a sample description for book 72.','https://example.com/thumbvol1072.jpg','https://example.com/previewvol1072');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1073','9780000000073','Sample Book Title 73','Author 73','Sample Publisher','2013','This is a sample description for book 73.','https://example.com/thumbvol1073.jpg','https://example.com/previewvol1073');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1074','9780000000074','Sample Book Title 74','Author 74','Sample Publisher','2014','This is a sample description for book 74.','https://example.com/thumbvol1074.jpg','https://example.com/previewvol1074');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1075','9780000000075','Sample Book Title 75','Author 75','Sample Publisher','2015','This is a sample description for book 75.','https://example.com/thumbvol1075.jpg','https://example.com/previewvol1075');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1076','9780000000076','Sample Book Title 76','Author 76','Sample Publisher','2016','This is a sample description for book 76.','https://example.com/thumbvol1076.jpg','https://example.com/previewvol1076');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1077','9780000000077','Sample Book Title 77','Author 77','Sample Publisher','2017','This is a sample description for book 77.','https://example.com/thumbvol1077.jpg','https://example.com/previewvol1077');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1078','9780000000078','Sample Book Title 78','Author 78','Sample Publisher','2018','This is a sample description for book 78.','https://example.com/thumbvol1078.jpg','https://example.com/previewvol1078');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1079','9780000000079','Sample Book Title 79','Author 79','Sample Publisher','2019','This is a sample description for book 79.','https://example.com/thumbvol1079.jpg','https://example.com/previewvol1079');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1080','9780000000080','Sample Book Title 80','Author 80','Sample Publisher','2000','This is a sample description for book 80.','https://example.com/thumbvol1080.jpg','https://example.com/previewvol1080');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1081','9780000000081','Sample Book Title 81','Author 81','Sample Publisher','2001','This is a sample description for book 81.','https://example.com/thumbvol1081.jpg','https://example.com/previewvol1081');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1082','9780000000082','Sample Book Title 82','Author 82','Sample Publisher','2002','This is a sample description for book 82.','https://example.com/thumbvol1082.jpg','https://example.com/previewvol1082');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1083','9780000000083','Sample Book Title 83','Author 83','Sample Publisher','2003','This is a sample description for book 83.','https://example.com/thumbvol1083.jpg','https://example.com/previewvol1083');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1084','9780000000084','Sample Book Title 84','Author 84','Sample Publisher','2004','This is a sample description for book 84.','https://example.com/thumbvol1084.jpg','https://example.com/previewvol1084');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1085','9780000000085','Sample Book Title 85','Author 85','Sample Publisher','2005','This is a sample description for book 85.','https://example.com/thumbvol1085.jpg','https://example.com/previewvol1085');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1086','9780000000086','Sample Book Title 86','Author 86','Sample Publisher','2006','This is a sample description for book 86.','https://example.com/thumbvol1086.jpg','https://example.com/previewvol1086');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1087','9780000000087','Sample Book Title 87','Author 87','Sample Publisher','2007','This is a sample description for book 87.','https://example.com/thumbvol1087.jpg','https://example.com/previewvol1087');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1088','9780000000088','Sample Book Title 88','Author 88','Sample Publisher','2008','This is a sample description for book 88.','https://example.com/thumbvol1088.jpg','https://example.com/previewvol1088');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1089','9780000000089','Sample Book Title 89','Author 89','Sample Publisher','2009','This is a sample description for book 89.','https://example.com/thumbvol1089.jpg','https://example.com/previewvol1089');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1090','9780000000090','Sample Book Title 90','Author 90','Sample Publisher','2010','This is a sample description for book 90.','https://example.com/thumbvol1090.jpg','https://example.com/previewvol1090');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1091','9780000000091','Sample Book Title 91','Author 91','Sample Publisher','2011','This is a sample description for book 91.','https://example.com/thumbvol1091.jpg','https://example.com/previewvol1091');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1092','9780000000092','Sample Book Title 92','Author 92','Sample Publisher','2012','This is a sample description for book 92.','https://example.com/thumbvol1092.jpg','https://example.com/previewvol1092');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1093','9780000000093','Sample Book Title 93','Author 93','Sample Publisher','2013','This is a sample description for book 93.','https://example.com/thumbvol1093.jpg','https://example.com/previewvol1093');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1094','9780000000094','Sample Book Title 94','Author 94','Sample Publisher','2014','This is a sample description for book 94.','https://example.com/thumbvol1094.jpg','https://example.com/previewvol1094');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1095','9780000000095','Sample Book Title 95','Author 95','Sample Publisher','2015','This is a sample description for book 95.','https://example.com/thumbvol1095.jpg','https://example.com/previewvol1095');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1096','9780000000096','Sample Book Title 96','Author 96','Sample Publisher','2016','This is a sample description for book 96.','https://example.com/thumbvol1096.jpg','https://example.com/previewvol1096');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1097','9780000000097','Sample Book Title 97','Author 97','Sample Publisher','2017','This is a sample description for book 97.','https://example.com/thumbvol1097.jpg','https://example.com/previewvol1097');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1098','9780000000098','Sample Book Title 98','Author 98','Sample Publisher','2018','This is a sample description for book 98.','https://example.com/thumbvol1098.jpg','https://example.com/previewvol1098');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1099','9780000000099','Sample Book Title 99','Author 99','Sample Publisher','2019','This is a sample description for book 99.','https://example.com/thumbvol1099.jpg','https://example.com/previewvol1099');
-- INSERT INTO books (google_volume_id,isbn,title,authors,publisher,published_date,description,thumbnail_link,preview_link) VALUES ('vol1100','9780000000100','Sample Book Title 100','Author 100','Sample Publisher','2000','This is a sample description for book 100.','https://example.com/thumbvol1100.jpg','https://example.com/previewvol1100');

-- user_books 200 entries

-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (50,55,'COMPLETED',1,'構成がしっかりしていて読みやすい一冊。','2022-09-16','2022-05-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,94,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,26,'PENDING',2,'構成がしっかりしていて読みやすい一冊。',NULL,'2022-10-22');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (29,46,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (25,36,'COMPLETED',3,'少し難しかった。','2024-05-14','2022-08-10');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,83,'WANT',3,'とても読みやすかった。',NULL,'2023-07-21');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,31,'COMPLETED',5,'ストーリーが丁寧に描かれていて引き込まれた。','2024-12-26','2022-03-17');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (15,24,'COMPLETED',1,'面白くて一気に読んだ。','2024-07-24','2024-11-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (27,22,'WANT',2,'少し難しかった。',NULL,'2023-12-04');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (25,60,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (5,54,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,33,'COMPLETED',2,'構成がしっかりしていて読みやすい一冊。','2023-01-18','2022-09-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,89,'WANT',5,'少し難しかった。',NULL,'2022-05-19');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (40,72,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (3,73,'COMPLETED',3,'構成がしっかりしていて読みやすい一冊。','2023-01-17','2023-12-28');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,27,'COMPLETED',4,'面白くて一気に読んだ。','2024-01-15','2023-06-02');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (13,77,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (1,5,'READING',5,'テンポが良い。',NULL,'2022-12-20');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (47,33,'COMPLETED',4,'構成がしっかりしていて読みやすい一冊。','2024-11-03','2022-03-17');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (22,95,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (39,50,'COMPLETED',5,'ストーリーが丁寧に描かれていて引き込まれた。','2023-04-27','2022-12-10');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (25,96,'READING',3,'構成がしっかりしていて読みやすい一冊。',NULL,'2023-01-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (45,78,'COMPLETED',1,'とても読みやすかった。','2023-07-03','2024-04-01');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,15,'WANT',1,'面白くて一気に読んだ。',NULL,'2022-06-28');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (43,10,'READING',5,'テンポが良い。',NULL,'2022-06-15');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (34,49,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (42,31,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,73,'COMPLETED',5,'とても読みやすかった。','2022-11-25','2022-08-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (12,72,'WANT',1,'テンポが良い。',NULL,'2022-01-05');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,4,'COMPLETED',4,'テンポが良い。','2022-04-18','2022-08-11');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (41,9,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (27,2,'COMPLETED',4,'テンポが良い。','2024-02-04','2022-02-11');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (35,38,'COMPLETED',5,'世界観が好き。','2024-12-18','2022-04-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,14,'PENDING',2,'構成がしっかりしていて読みやすい一冊。',NULL,'2023-10-25');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,6,'READING',5,'とても読みやすかった。',NULL,'2022-08-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (34,2,'PENDING',4,'面白くて一気に読んだ。',NULL,'2022-12-16');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (29,74,'READING',3,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2024-01-10');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (48,44,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (49,72,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (8,83,'COMPLETED',4,'とても読みやすかった。','2022-06-09','2023-08-14');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (32,27,'PENDING',3,'少し難しかった。',NULL,'2023-02-06');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,31,'COMPLETED',2,'構成がしっかりしていて読みやすい一冊。','2022-07-10','2022-05-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,33,'READING',1,'構成がしっかりしていて読みやすい一冊。',NULL,'2022-05-25');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (33,43,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (43,90,'COMPLETED',2,'少し難しかった。','2023-12-14','2022-05-21');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,48,'COMPLETED',4,'構成がしっかりしていて読みやすい一冊。','2024-10-19','2022-09-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (3,38,'COMPLETED',4,'少し難しかった。','2024-01-05','2023-02-05');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (39,34,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (10,96,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (40,69,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (39,87,'READING',1,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2022-08-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (29,78,'READING',4,'世界観が好き。',NULL,'2023-06-14');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (33,75,'COMPLETED',4,'構成がしっかりしていて読みやすい一冊。','2024-05-17','2023-12-22');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,53,'WANT',5,'構成がしっかりしていて読みやすい一冊。',NULL,'2022-09-05');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,68,'PENDING',3,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2023-12-03');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (31,71,'READING',3,'構成がしっかりしていて読みやすい一冊。',NULL,'2023-02-20');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (29,10,'READING',5,'構成がしっかりしていて読みやすい一冊。',NULL,'2023-07-26');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (25,4,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (9,14,'COMPLETED',2,'キャラクターの心情表現がとても良かった。','2023-08-15','2024-08-14');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (31,70,'PENDING',3,'世界観が好き。',NULL,'2022-04-11');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (29,82,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (42,59,'COMPLETED',3,'構成がしっかりしていて読みやすい一冊。','2022-01-10','2023-09-26');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (43,49,'READING',3,'とても読みやすかった。',NULL,'2023-10-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (37,43,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,29,'COMPLETED',3,'少し難しかった。','2022-09-01','2022-05-03');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (47,26,'WANT',5,'少し難しかった。',NULL,'2023-04-04');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (10,50,'READING',2,'テンポが良い。',NULL,'2024-10-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (38,83,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (39,54,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (41,10,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,87,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (39,79,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (47,37,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (9,99,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (12,92,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (23,12,'WANT',5,'少し難しかった。',NULL,'2024-06-06');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (35,81,'COMPLETED',3,'とても読みやすかった。','2024-09-13','2024-06-28');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (39,53,'PENDING',5,'世界観が好き。',NULL,'2023-12-05');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (28,48,'READING',1,'世界観が好き。',NULL,'2022-03-02');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (25,72,'COMPLETED',2,'キャラクターの心情表現がとても良かった。','2023-12-08','2023-08-13');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (28,90,'WANT',3,'とても読みやすかった。',NULL,'2022-11-12');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (5,99,'WANT',2,'世界観が好き。',NULL,'2023-12-14');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,27,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,66,'READING',3,'面白くて一気に読んだ。',NULL,'2022-06-28');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,91,'COMPLETED',5,'世界観が好き。','2022-10-01','2023-06-10');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (2,29,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (38,69,'COMPLETED',3,'面白くて一気に読んだ。','2024-09-27','2023-07-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (22,69,'COMPLETED',1,'世界観が好き。','2022-09-19','2022-03-27');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (8,11,'WANT',4,'とても読みやすかった。',NULL,'2023-11-26');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,48,'COMPLETED',5,'面白くて一気に読んだ。','2022-07-07','2022-06-14');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,62,'READING',4,'キャラクターの心情表現がとても良かった。',NULL,'2023-06-21');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (26,92,'COMPLETED',3,'ストーリーが丁寧に描かれていて引き込まれた。','2023-05-17','2022-08-05');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (2,18,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (35,87,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (9,55,'PENDING',3,'面白くて一気に読んだ。',NULL,'2023-11-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,37,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (28,5,'COMPLETED',5,'構成がしっかりしていて読みやすい一冊。','2022-03-09','2024-12-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (43,75,'READING',3,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2022-10-04');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (6,94,'WANT',5,'面白くて一気に読んだ。',NULL,'2022-01-22');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,38,'READING',1,'世界観が好き。',NULL,'2024-06-05');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (9,51,'COMPLETED',1,'とても読みやすかった。','2024-02-01','2024-08-11');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (50,37,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,42,'READING',5,'構成がしっかりしていて読みやすい一冊。',NULL,'2024-11-06');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,87,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (41,87,'COMPLETED',1,'テンポが良い。','2024-05-16','2022-03-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,1,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (8,71,'COMPLETED',4,'世界観が好き。','2024-04-26','2022-10-17');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (46,38,'READING',5,'キャラクターの心情表現がとても良かった。',NULL,'2022-07-18');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (31,49,'COMPLETED',5,'構成がしっかりしていて読みやすい一冊。','2024-08-20','2022-09-27');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (37,37,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,81,'COMPLETED',1,'世界観が好き。','2024-07-08','2023-07-27');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (15,8,'WANT',5,'テンポが良い。',NULL,'2023-08-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,50,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (18,82,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (26,23,'WANT',1,'とても読みやすかった。',NULL,'2023-06-02');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (12,78,'COMPLETED',1,'とても読みやすかった。','2024-03-26','2022-09-15');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (21,35,'PENDING',4,'少し難しかった。',NULL,'2024-06-02');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (12,13,'WANT',1,'キャラクターの心情表現がとても良かった。',NULL,'2023-06-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,19,'READING',3,'少し難しかった。',NULL,'2023-07-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (33,59,'WANT',4,'少し難しかった。',NULL,'2024-06-28');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,21,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (26,98,'WANT',4,'とても読みやすかった。',NULL,'2023-12-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (40,90,'PENDING',3,'構成がしっかりしていて読みやすい一冊。',NULL,'2022-04-13');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,31,'READING',5,'テンポが良い。',NULL,'2022-11-20');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,23,'COMPLETED',3,'テンポが良い。','2022-06-11','2022-07-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,99,'WANT',5,'テンポが良い。',NULL,'2022-05-04');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (18,13,'READING',1,'とても読みやすかった。',NULL,'2023-02-26');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,30,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (31,27,'PENDING',3,'とても読みやすかった。',NULL,'2022-02-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (48,22,'PENDING',4,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2023-09-26');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (1,6,'READING',5,'とても読みやすかった。',NULL,'2022-10-01');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,28,'COMPLETED',1,'少し難しかった。','2022-07-09','2023-04-19');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (50,28,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (1,52,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (24,19,'COMPLETED',3,'世界観が好き。','2024-11-21','2023-09-06');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (4,51,'WANT',3,'構成がしっかりしていて読みやすい一冊。',NULL,'2022-08-13');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (38,29,'COMPLETED',1,'構成がしっかりしていて読みやすい一冊。','2022-02-03','2023-06-11');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,79,'COMPLETED',1,'構成がしっかりしていて読みやすい一冊。','2022-03-05','2022-01-20');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (22,51,'COMPLETED',3,'面白くて一気に読んだ。','2024-10-14','2023-06-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (10,90,'WANT',4,'テンポが良い。',NULL,'2023-05-13');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (16,53,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (46,82,'WANT',1,'少し難しかった。',NULL,'2023-03-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (7,4,'PENDING',1,'面白くて一気に読んだ。',NULL,'2024-05-01');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (26,28,'READING',3,'とても読みやすかった。',NULL,'2022-05-04');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (32,3,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (10,5,'WANT',4,'テンポが良い。',NULL,'2024-05-07');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,75,'READING',3,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2024-11-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,24,'READING',2,'構成がしっかりしていて読みやすい一冊。',NULL,'2022-06-03');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (22,3,'COMPLETED',3,'構成がしっかりしていて読みやすい一冊。','2022-07-09','2022-04-03');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (26,46,'COMPLETED',5,'ストーリーが丁寧に描かれていて引き込まれた。','2024-03-19','2023-03-11');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (20,100,'COMPLETED',2,'世界観が好き。','2023-11-21','2024-07-12');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (31,37,'WANT',4,'少し難しかった。',NULL,'2022-02-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (19,36,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (12,69,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,100,'COMPLETED',2,'構成がしっかりしていて読みやすい一冊。','2022-01-25','2023-06-22');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,41,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (47,25,'READING',2,'世界観が好き。',NULL,'2024-02-17');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (4,63,'COMPLETED',2,'ストーリーが丁寧に描かれていて引き込まれた。','2023-06-11','2023-12-12');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,19,'READING',4,'世界観が好き。',NULL,'2023-12-16');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (38,16,'READING',5,'とても読みやすかった。',NULL,'2022-01-13');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (20,46,'READING',2,'構成がしっかりしていて読みやすい一冊。',NULL,'2024-11-06');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (43,63,'COMPLETED',5,'世界観が好き。','2022-06-18','2024-08-06');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,59,'COMPLETED',2,'構成がしっかりしていて読みやすい一冊。','2023-08-14','2022-04-10');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,30,'COMPLETED',3,'構成がしっかりしていて読みやすい一冊。','2024-03-05','2024-12-19');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (22,47,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (16,50,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,34,'COMPLETED',5,'テンポが良い。','2024-12-16','2022-10-08');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (48,67,'WANT',5,'とても読みやすかった。',NULL,'2023-02-18');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (3,22,'COMPLETED',1,'世界観が好き。','2022-11-26','2024-03-19');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (20,49,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (44,94,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (35,74,'COMPLETED',4,'世界観が好き。','2022-08-15','2023-04-16');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (38,67,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (17,34,'COMPLETED',1,'ストーリーが丁寧に描かれていて引き込まれた。','2024-01-15','2024-04-24');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (3,43,'READING',2,'面白くて一気に読んだ。',NULL,'2024-06-02');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (6,2,'PENDING',4,'面白くて一気に読んだ。',NULL,'2022-02-21');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (22,21,'READING',3,'世界観が好き。',NULL,'2024-10-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,63,'COMPLETED',2,'面白くて一気に読んだ。','2023-06-24','2023-08-27');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (8,20,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (29,87,'READING',3,'キャラクターの心情表現がとても良かった。',NULL,'2024-08-12');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (47,36,'PENDING',4,'世界観が好き。',NULL,'2024-01-08');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (14,22,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (14,76,'WANT',3,'世界観が好き。',NULL,'2022-04-18');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (48,42,'READING',2,'ストーリーが丁寧に描かれていて引き込まれた。',NULL,'2022-09-01');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (18,86,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (33,3,'WANT',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,14,'PENDING',3,'構成がしっかりしていて読みやすい一冊。',NULL,'2023-12-02');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (24,25,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (36,73,'WANT',5,'構成がしっかりしていて読みやすい一冊。',NULL,'2023-11-09');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (45,94,'PENDING',1,'少し難しかった。',NULL,'2024-06-28');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (35,9,'COMPLETED',1,'構成がしっかりしていて読みやすい一冊。','2024-08-01','2022-07-04');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (24,21,'COMPLETED',3,'構成がしっかりしていて読みやすい一冊。','2023-11-18','2022-06-13');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (50,4,'COMPLETED',4,'構成がしっかりしていて読みやすい一冊。','2024-12-15','2023-03-23');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (28,98,'PENDING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (46,73,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (30,28,'COMPLETED',3,'世界観が好き。','2022-03-09','2023-01-22');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (33,55,'READING',NULL,NULL,NULL,NULL);
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (41,12,'WANT',3,'世界観が好き。',NULL,'2023-02-19');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (23,21,'COMPLETED',4,'キャラクターの心情表現がとても良かった。','2022-06-21','2023-05-12');
-- INSERT INTO user_books (user_id,book_id,status,rating,review,finished_at,review_updated_at) VALUES (38,62,'COMPLETED',2,'面白くて一気に読んだ。','2022-02-04','2024-03-08');



-- select*
-- from users u
-- join user_profiles up
-- on u.user_id = up.user_id;

-- select *
-- from user_books u
-- join books b
-- on u.book_id =b.id; 