CREATE DATABASE libris
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE users(
user_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
login_id VARCHAR(191) NOT NULL UNIQUE COLLATE utf8mb4_0900_as_cs,
password_hash CHAR(60) NOT NULL,
authority ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
display_name VARCHAR(50) NOT NULL,
status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT'ACTIVE',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE user_profiles(
user_id BIGINT NOT NULL PRIMARY KEY,
last_name VARCHAR(50) NOT NULL,
first_name VARCHAR(50) NOT NULL,
last_name_kana VARCHAR(50) NOT NULL,
first_name_kana VARCHAR(50) NOT NULL,
postal_code VARCHAR(10) NOT NULL,
prefecture VARCHAR(50) NOT NULL,
city VARCHAR(50) NOT NULL,
town VARCHAR(50) NOT NULL,
address_number VARCHAR(50) NOT NULL,
building VARCHAR(50),
birthday DATE NOT NULL,
phone_number VARCHAR(15),
email VARCHAR(191) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_user_profiles
FOREIGN KEY (user_id)
REFERENCES users(user_id)
);

CREATE TABLE books(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
google_volume_id VARCHAR(191) NOT NULL UNIQUE COLLATE utf8mb4_0900_as_cs,
isbn VARCHAR(20),
title VARCHAR(255) NOT NULL,
authors VARCHAR(500),
publisher VARCHAR(255),
published_date VARCHAR(20),
description TEXT,
thumbnail_link VARCHAR(500),
preview_link VARCHAR(500),
status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_books(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
book_id BIGINT NOT NULL,
status ENUM('WANT','READING','COMPLETED','PENDING') NOT NULL DEFAULT 'WANT',
rating INT,
review TEXT,
finished_at DATE,
review_updated_at DATETIME,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uk_user_books (user_id, book_id),
CONSTRAINT fk_user_books_user
FOREIGN KEY (user_id)
REFERENCES users(user_id),
CONSTRAINT fk_user_books_book
FOREIGN KEY (book_id)
REFERENCES books(id));










